ROBO/ROBO/Controllers/Robo/RoboController.cs
using Microsoft.AspNetCore.Mvc;
using ROBO.Models.Aplicacao;
using ROBO.Models.Dominio;

namespace ROBO.Controllers
{
    public class RoboController : Controller
    {
        private readonly IAplicControlaRoboBecomex _aplicControlaRoboBecomex;

        public RoboController(IAplicControlaRoboBecomex aplicControlaRoboBecomex)
        {
            _aplicControlaRoboBecomex = aplicControlaRoboBecomex;
        }

        public IActionResult Inicio()
        {
            return View();
        }

        public IActionResult TelaRobo()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Novo()
        {
            try
            {
                var robo = _aplicControlaRoboBecomex.Novo();
                return Ok(new HttpRetorno(true, "Robo criado com sucesso.", robo));
            }
            catch (Exception ex)
            {
                return BadRequest(new HttpRetorno(false, ex.Message, null));
            }
        }

        [HttpPost]
        public IActionResult Reseta([FromBody] RoboBecomex roboBecomex)
        {
            try
            {
                 var robo = _aplicControlaRoboBecomex.Reseta(roboBecomex);
                return Ok(new HttpRetorno(true, "Robo reiniciado com sucesso.", robo));
            }
            catch (Exception ex)
            {
                return BadRequest(new HttpRetorno(false, ex.Message, null));
            }
        }

        [HttpPut]
        public IActionResult Alterar([FromBody] RoboBecomex roboBecomex)
        {
            try
            {
                var robo = _aplicControlaRoboBecomex.Alterar(roboBecomex);
                return Ok(new HttpRetorno(true, "Robo Atualizado com sucesso.", robo));
            }
            catch (Exception ex)
            {
                return BadRequest(new HttpRetorno(false, ex.Message, null));
            }
        }

        [HttpPost]
        public IActionResult InclinaCabeca([FromBody] MovimentaCabecaDTO movimentaCabecaDTO)
        {
            try
            {
                var robo = _aplicControlaRoboBecomex.InclinaCabeca(movimentaCabecaDTO);
                return Ok(new HttpRetorno(true, "Ação executada com sucesso.", robo));
            }
            catch (Exception ex)
            {
                return BadRequest(new HttpRetorno(false, ex.Message, null));
            }
        }

        [HttpPost]
        public IActionResult RotacionaCabeca([FromBody] MovimentaCabecaDTO movimentaCabecaDTO)
        {
            try
            {
                var robo = _aplicControlaRoboBecomex.RotacionaCabeca(movimentaCabecaDTO);
                return Ok(new HttpRetorno(true, "Ação executada com sucesso.", robo));
            }
            catch (Exception ex)
            {
                return BadRequest(new HttpRetorno(false, ex.Message, null));
            }
        }

        [HttpPost]
        public IActionResult MoveCotovelo([FromBody] MovimentaBracoDTO movimentaBracoDTO)
        {
            try
            {
                var robo = _aplicControlaRoboBecomex.MoveCotovelo(movimentaBracoDTO);
                return Ok(new HttpRetorno(true, "Ação executada com sucesso.", robo));
            }
            catch (Exception ex)
            {
                return BadRequest(new HttpRetorno(false, ex.Message, null));
            }
        }

        [HttpPost]
        public IActionResult RotacionaPulso([FromBody] MovimentaBracoDTO movimentaBracoDTO)
        {
            try
            {
                var robo = _aplicControlaRoboBecomex.RotacionaPulso(movimentaBracoDTO);
                return Ok(new HttpRetorno(true, "Ação executada com sucesso.", robo));
            }
            catch (Exception ex)
            {
                return BadRequest(new HttpRetorno(false, ex.Message, null));
            }
        }
    }
}

ROBO/ROBO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ROBO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ROBO.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark bg-gradient">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Robo" asp-action="Inicio">BECOMEX</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Robo" asp-action="Inicio">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white-50 bg-dark">
        <div class="container">
            &copy; @DateTime.Now.Year - R.O.B.O - Artini Scarabelot
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>